version = 0.1
[default.deploy.parameters]
stack_name = "image-processing-stack"
resolve_s3 = true
s3_prefix = "image-processing-stack"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
