AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Processing Pipeline

Resources:
  DetectLabel:
  Type: AWS::Serverless::Application
  Properties:
    Location: ./functions/detect-labels
  
  GenerateThumbnails:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./functions/generate-thumbnails
  StoreMetadata:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./functions/store-metadata