AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  StoreMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: store-metadata
      Handler: main
      CodeUri: .
      Runtime: go1.x
      Policies:
        - AmazonDynamoDBFullAccess # Adjust to fine-grained permissions if needed
      Environment:
        Variables:
          TABLE_NAME: ImageMetadata
Outputs:
  StoreMetadataFunctionArn:
    Value:
      Fn::GetAtt:
        - StoreMetadataFunction
        - Arn
